-- SQL STATEMENTS
--- DML
---- SELECT
----- FROM clause
----- WHERE clause
----- AND / OR clauses
----- JOIN clauses: INNER, OUTER LEFT, OUTER RIGHT, SELF, NATURAL, CROSS, EQUI, etc.
----- CASE clause
----- Single row functions (SRF): trunc, cat, etc.
----- Aggregate functions (input multiple rows, output one row): count, max, min, sum, avg, GROUP BY ... HAVING, 
----- Analytical functions (input multiple rows, output multiple rows): over, partition by, order by
---- INSERT
---- UPDATE
---- DELETE