SELECT EMP.ENAME, EMP.JOB, EMP.SAL, DEPT.LOC
FROM EMP, DEPT
WHERE DEPT.LOC = 'DALLAS';

SELECT EMP.ENAME, EMP.JOB, EMP.SAL, DEPT.LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND DEPT.LOC = 'DALLAS';

SELECT * FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND DEPT.LOC = 'DALLAS';

SELECT * FROM DEPT d, EMP e 
WHERE d.DEPTNO = e.DEPTNO;